version: '3.8'

services:
  radix-dashboard:
    build: .
    container_name: radix-telemetry-ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
